export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'; 
export const SELECT_USER_SUCCESS = 'SELECT_USER_SUCCESS';
export const GET_WORK_BY_USER_SUCCESS = 'GET_WORK_BY_USER_SUCCESS';
export const UPDATE_SELECTED_MONTH_SUCCESS = 'UPDATE_SELECTED_MONTH_SUCCESS';
export const UPDATE_SELECTED_YEAR_SUCCESS = 'UPDATE_SELECTED_YEAR_SUCCESS';
export const UPDATE_SELECTED_WEEK_SUCCESS = 'UPDATE_SELECTED_WEEK_SUCCESS';
export const UPDATE_WEEK_STATUS_SUCCESS = 'UPDATE_WEEK_STATUS_SUCCESS'; 

export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const SELECT_USER_ERROR = 'SELECT_USER_ERROR';
export const GET_WORK_BY_USER_ERROR = 'GET_WORK_BY_USER_ERROR';
export const UPDATE_SELECTED_MONTH_ERROR = 'UPDATE_SELECTED_MONTH_ERROR';
export const UPDATE_SELECTED_YEAR_ERROR = 'UPDATE_SELECTED_YEAR_ERROR';
export const UPDATE_SELECTED_WEEK_ERROR = 'UPDATE_SELECTED_WEEK_ERROR';
export const UPDATE_WEEK_STATUS_ERROR = 'UPDATE_WEEK_STATUS_ERROR'; 