export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'; 
export const SELECT_USER_SUCCESS = 'SELECT_USER_SUCCESS';
export const GET_WORK_BY_USER_SUCCESS = 'GET_WORK_BY_USER_SUCCESS';
export const UPDATE_SELECTED_MONTH_SUCCESS = 'UPDATE_SELECTED_MONTH_SUCCESS';
export const UPDATE_SELECTED_YEAR_SUCCESS = 'UPDATE_SELECTED_YEAR_SUCCESS';
export const UPDATE_SELECTED_WEEK_SUCCESS = 'UPDATE_SELECTED_WEEK_SUCCESS';
export const UPDATE_WEEK_STATUS_SUCCESS = 'UPDATE_WEEK_STATUS_SUCCESS'; 
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';